apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: booking-service-secrets
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: booking-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: booking-service-secrets
